import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import AuthProvider from "../../Provider/AuthProvider";
import AgeVerification from "../../components/AgeVerification";

const josefinSans = Josefin_Sans({
  variable: "--font-primary",
  subsets: ["latin"],
  display: "swap",
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${josefinSans.variable} antialiased bg-purple-50`}>
        <AuthProvider>
          <AgeVerification />
         <Navbar></Navbar>
        {children}
        <Footer />
        </AuthProvider>
       
      </body>
    </html>
  );
}
