'use client' // needed because we’ll use usePathname()

import { Josefin_Sans } from 'next/font/google'
import './globals.css'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import AuthProvider from '../../Provider/AuthProvider'
import AgeVerification from '../../components/AgeVerification'

import { usePathname } from 'next/navigation' // 👈 import hook

const josefinSans = Josefin_Sans({
  variable: '--font-primary',
  subsets: ['latin'],
  display: 'swap',
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const pathname = usePathname()
  const isAdminRoute = pathname.startsWith('/admin') // 👈 detect admin

  return (
    <html lang="en">
      <body className={`${josefinSans.variable} antialiased bg-purple-50`}>
        <AuthProvider>
          {!isAdminRoute && <AgeVerification />}
          {!isAdminRoute && <Navbar />}
          {children}
          {!isAdminRoute && <Footer />}
        </AuthProvider>
      </body>
    </html>
  )
}
